Schema verification test
EURODEO/e-soh-event-queue pull request #6
Opened 2023-08-22 07:59 UTC by Teddy-1000

Closes #5:Implemented test json schema validation for mqtt payloads created from netCDF files. 
The test implemented verifies that all .nc files creates valid json payloads.
Also fixed an error in formatting the mqtt message schema where some properties should be strings, with "," separation, not arrays.

Also add VS code files to the .gitignore

2023-08-23 12:30 UTC, mortenwh approved these changes
Looks good!

2023-08-23 12:30 UTC, mortenwh commented on examples/air_temperature_gullingen_skisenter-parent_meta.json
> +        "data_id": "8a0744b7-f0dc-4929-8700-f1285e76df36",
Should be on the form "\<naming_authority\>:\<uuid\>" now, right? Also it should not be the same as the `metadata_id`, which we agreed should refer to the parent dataset metadata?

2023-08-23 12:30 UTC, mortenwh commented on examples/air_temperature_gullingen_skisenter-parent_meta.json
> +        "history": "2023-06-14T14:38:30.363447+00:00: Created from Frost.",
Now, this should not be the same as the history in the nc-file. I think it is enough to give the time the message was created, i.e., `"history": "<timestamp>: Created"`.

2023-08-23 12:30 UTC, mortenwh commented on examples/air_temperature_gullingen_skisenter-parent_meta.json
> +        "history": "2023-06-14T14:38:30.363447+00:00: Created from Frost.",
maybe it is not strictly needed either, but I think it is required in CF convention. BTW: can you also check the CF-JSON standard?

2023-08-23 12:30 UTC, mortenwh commented on pyproject.toml
> +description = "Code for parsing and publshing metadata to the E-SOH members"
```suggestion
description = "Code for parsing and publishing metadata to the E-SOH members"
```

2023-08-23 12:31 UTC, mortenwh requested changes
Sorry - some small things...

2023-08-23 13:07 UTC, Teddy-1000 commented on examples/air_temperature_gullingen_skisenter-parent_meta.json
> +        "history": "2023-06-14T14:38:30.363447+00:00: Created from Frost.",
It is required in both standards, but we could drop it from the MQTT message, but keep it in the metadata we submit to the datastore.

From CF:
```
history
Provides an audit trail for modifications to the original data. Well-behaved generic netCDF filters will automatically append their name and the parameters with which they were invoked to the global history attribute of an input netCDF file. We recommend that each line begin with a timestamp indicating the date and time of day that the program was executed.
```
From ACDD:
```
Provides an audit trail for modifications to the original data. This attribute is also in the [NetCDF Users Guide](http://www.unidata.ucar.edu/software/netcdf/docs/netcdf.html#Attribute-Conventions): 'This is a character array with a line for each invocation of a program that has modified the dataset. Well-behaved generic netCDF applications should append a line containing: date, time of day, user name, program name and command arguments.' To include a more complete description you can append a reference to an ISO Lineage entity; see [NOAA EDM ISO Lineage guidance](https://geo-ide.noaa.gov/wiki/index.php?title=ISO_Lineage).
```

2023-08-23 13:24 UTC, Teddy-1000 commented on examples/air_temperature_gullingen_skisenter-parent_meta.json
> +        "data_id": "8a0744b7-f0dc-4929-8700-f1285e76df36",
For now this is just a placeholder value, and we will generate some new uuid for this field. I also suggest that this id is correlated to the datastore somehow, but this can be discussed later.

2023-08-24 10:40 UTC, Teddy-1000 commented on examples/air_temperature_gullingen_skisenter-parent_meta.json
> +        "history": "2023-06-14T14:38:30.363447+00:00: Created from Frost.",
This should also be changed in a separate issue. I will resolve this, and we can rather create a new issuse for this problem.

2023-08-25 06:33 UTC, mortenwh commented on examples/air_temperature_gullingen_skisenter-parent_meta.json
> +        "history": "2023-06-14T14:38:30.363447+00:00: Created from Frost.",
ok, I think it would be good to keep what's in the data store and what comes through the queue identical, so let's keep it

2023-08-25 06:34 UTC, mortenwh approved these changes

2023-08-25 06:54 UTC, merged